services:
  wem.grid.classes.grid_elements_wrapper:
    class: WEM\GridBundle\Classes\GridElementsWrapper
    arguments:
      $translator: '@contao.translation.translator'
      $gridBuilder: '@wem.grid.helper.grid_builder'
    public: true

  wem.grid.classes.grid_start_manipulator:
    class: WEM\GridBundle\Classes\GridStartManipulator
    arguments:
      $gridElementsCalculator: '@wem.grid.classes.grid_elements_calculator'
    public: true

  wem.grid.classes.grid_elements_calculator:
    class: WEM\GridBundle\Classes\GridElementsCalculator
    public: true

  wem.grid.helper.tl_content_callback:
    class: WEM\GridBundle\Helper\tlContentCallback
    arguments:
      $gridElementsCalculator: '@wem.grid.classes.grid_elements_calculator'
    public: true

  wem.grid.helper.grid_builder:
    class: WEM\GridBundle\Helper\GridBuilder
    public: true